language: erlang
otp_release:
  - R16B01
  - R16B02

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ruby-dev build-essential
  - sudo gem install fpm  --no-rdoc
script: make deps tests package
