language: erlang
otp_release:
  - R16B01
  - R16B02

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ruby ruby-dev rubygems build-essential
  - sudo adduser etsdb --system
install:
  - gem install fpm
script: make deps tests package
